#!/usr/bin/python
import sys
import time
from subprocess import check_output


if len(sys.argv) > 1 and sys.argv[1] == 'start':
    h = int(time.strftime('%H'))
    if 8 <= h < 22:
        check_output('/home/l31rb4g/raspberry/switch.py 1 on', shell=True)
